language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9', 'libfuse-dev']
      env:
        - COMPILER=g++-4.9
        - LTO_FLAG=-flto

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'libfuse-dev']
      env:
        - COMPILER=g++-5
        - LTO_FLAG=-flto

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6', 'libfuse-dev']
      env:
        - COMPILER=g++-6
        - LTO_FLAG=-flto

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7', 'libfuse-dev']
      env:
        - COMPILER=g++-7
        - LTO_FLAG=-flto

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-3.9']
          packages: ['clang-3.9', 'libstdc++-4.9-dev', 'libfuse-dev']
      env:
        - COMPILER=clang++-3.9
        - LTO_FLAG=

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0', 'libstdc++-4.9-dev', 'libfuse-dev']
      env:
        - COMPILER=clang++-4.0
        - LTO_FLAG=

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env:
        - COMPILER=clang++
        - LTO_FLAG=-flto
        - IMAGE="FUSE for macOS"
        - IMAGEURL=https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.8.3/osxfuse-3.8.3.dmg

    - os: osx
      osx_image: xcode9
      compiler: clang
      env:
        - COMPILER=clang++
        - LTO_FLAG=-flto
        - IMAGE="FUSE for macOS"
        - IMAGEURL=https://github.com/osxfuse/osxfuse/releases/download/osxfuse-3.8.3/osxfuse-3.8.3.dmg

install:
  - if [ $TRAVIS_OS_NAME = "osx" ]; then curl -L -# -C - -o $IMAGE.dmg $IMAGEURL;ls -lh $IMAGE.dmg;sudo hdiutil attach $IMAGE.dmg;sudo installer -package /Volumes/$IMAGE/$IMAGE.pkg -target /;sudo hdiutil detach /Volumes/$IMAGE; fi
git:
  submodules: true
script:
  - make -f Makefile.travis CXX=$COMPILER LTO_FLAG=$LTO_FLAG DEFINES=-D__CONTINUOUS_INTEGRATION__ VERBOSE=true 

